# Generated by Django 5.2.1 on 2025-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspermission',
            old_name='expires_at',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
